version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: react-redux
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env

