export const SET_USER = "SET_USER";
export const USERS_ERROR = "USERS_ERROR";
export const CURRENT_USER = "CURRENT_USER";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const RETRIVE_CATEGORY = "RETRIVE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
